// Review of HiddenHawk615's Talagrand SK overlap submission, 14 Aug 2026.
//
// Verified against the paper's LaTeX source (arXiv:2608.08752) and the
// prior-art source (Dey-Kang, arXiv:2603.05636), both fetched and read:
//   - "The following corollary affirmatively resolves [Conjecture 11.7.5]"
//     appears verbatim, attached to Corollary c:main;
//   - the AI-role section says most formal arguments were initially
//     generated by GPT-5.6 Pro and names the principal human inputs (the
//     limiting objects, the sphere-to-cube theorem, the overall strategy);
//     the technical body separately credits a specific step to the model
//     ("using an idea due to GPT-5.6 Pro", the Hilbert-space kernel trick) -
//     named model steps inside a human-led strategy is ai-co-developed's
//     definition, so the submitter's conservative call is confirmed rather
//     than merely tolerated;
//   - Dey-Kang (March 2026) quotes Conjecture 11.7.5 with exactly the
//     submitted statement and treats it as open, which pins the prior state.
//
// One axis change, same policy as every recent case: Candidate -> Resolved,
// since Preprint + Unreviewed already carries the not-yet-refereed fact and
// Candidate is reserved for claims awaiting a specific arbiter.
//
// Dry run by default. Pass --apply to write.

import { PrismaClient } from "@prisma/client";
import { CURATOR_FIELDS, EDITABLE_FIELDS } from "../src/lib/editable";
import { MESSAGE_MAX } from "../src/lib/messages";

const prisma = new PrismaClient();
const APPLY = process.argv.includes("--apply");

const ADMIN_EMAIL = "rasmus.lindahl1996@gmail.com";
const SLUG = "talagrand-s-critical-sherrington-kirkpatrick-overlap-conjecture";

const LIMITS = new Map<string, number>();
for (const s of [...EDITABLE_FIELDS, ...CURATOR_FIELDS]) {
  if (s.maxLength) LIMITS.set(s.key, s.maxLength);
}

const EDITS: { field: string; key: string; value: unknown }[] = [
  { field: "Status", key: "resolution", value: "resolved" },
  {
    field: "Verification note",
    key: "verificationNote",
    value:
      "Checked by this site on 14 August 2026 against the paper's LaTeX source and the prior-art source, both fetched and read. Confirmed verbatim in the paper: \"The following corollary affirmatively resolves [Conjecture 11.7.5]\", attached to the corollary giving $\\lim N^{2/3}\\mathbb{E}\\langle R_{1,2}^2\\rangle$ as the mean of an explicit positive random variable built from the reflected $Airy_1$ process. The prior state is independently pinned: Dey and Kang (arXiv:2603.05636, March 2026) quote Conjecture 11.7.5 with exactly the statement submitted here and treat it as open. The AI disclosure was read in full: most formal arguments were initially generated by GPT-5.6 Pro, the principal human inputs are named (identification of the limiting objects, formulation of the sphere-to-cube comparison theorem, and the overall proof strategy), and the technical body separately credits one step to the model by name - the Hilbert-space kernel argument upgrading the Laplace-transform comparison is introduced as \"an idea due to GPT-5.6 Pro\". What was NOT checked here is the mathematics itself: a 36-page argument through the $Airy_1$ scaling limit at the GOE spectral edge needs a spin-glass or random-matrix specialist. The manuscript is five days old, unrefereed, and the authors taking responsibility for correctness is author-side checking, so the tier stays Unreviewed.",
  },
  { field: "Significance", key: "significance", value: 30 },
  {
    field: "Significance note",
    key: "significanceNote",
    value:
      "A named conjecture of Michel Talagrand from his standard monograph (Mean Field Models for Spin Glasses, vol. II, 2011), open fifteen years and quoted as open in the literature five months before this proof. Critical-point overlap scaling is a celebrated question inside spin-glass theory but specialist territory outside it: a technical conjecture from the book, not one of the field's headline problems. Placed with the strong specialist conjectures at 30, below the field-famous band of Krauth-Mezard and Feige at 35.",
  },
  {
    field: "Age note",
    key: "ageNote",
    value:
      "Posed in Talagrand's Mean Field Models for Spin Glasses, volume II (2011), as Conjecture 11.7.5, alongside his theorems locating the transition window at width N^(-1/3). Open fifteen years; Dey and Kang still cite it as open in March 2026, five months before this proof.",
  },
];

const LINKS = [
  {
    label: "Dey and Kang (arXiv:2603.05636) - quotes Conjecture 11.7.5 as open, five months before this proof",
    url: "https://arxiv.org/abs/2603.05636",
    kind: "problem-record",
  },
  {
    label: "Du and Huang's companion paper on critical SK free-energy fluctuations, whose ideas this work extends",
    url: "https://arxiv.org/abs/2607.02172",
    kind: "paper",
  },
];

const MESSAGE = `Published, with one axis moved and the rest as submitted - this is another textbook submission, and your conservative tier call turned out to be exactly right for a reason you'll like.

I fetched the paper's LaTeX and read the AI-role section in full. It does more than say "most of the arguments were generated using GPT-5.6 Pro": it names the principal human inputs (the limiting objects, the sphere-to-cube comparison theorem, the overall proof strategy), and the technical body separately credits one step to the model by name - the Hilbert-space kernel trick upgrading the Laplace-transform comparison is introduced as "an idea due to GPT-5.6 Pro". Named model steps inside a human-led strategy is the ai-co-developed definition almost word for word, so your pick is confirmed rather than merely accepted.

Your prior-art evidence also checks out precisely: Dey-Kang quote Conjecture 11.7.5 with exactly your statement and treat it as open, in March 2026. That pins the before-state better than most submissions manage.

The one change: Candidate to Resolved, same policy as your Gamow-adjacent cases - the catalog reserves Candidate for claims awaiting a specific arbiter, and Preprint + Unreviewed already says nobody independent has checked it. What I could not check is the mathematics: 36 pages through the Airy_1 scaling limit at the GOE edge needs a spin-glass specialist, so Unreviewed stands.

Significance 30: a named Talagrand conjecture from the standard monograph, open fifteen years - but a technical conjecture from the book rather than a headline problem of the field, so it sits with the strong specialist band, below Krauth-Mezard and Feige at 35. Added an age note and links to Dey-Kang and the companion paper.`;

async function main() {
  const admin = await prisma.user.findUnique({ where: { email: ADMIN_EMAIL } });
  if (!admin) throw new Error(`no admin user for ${ADMIN_EMAIL}`);

  const p = await prisma.problem.findUnique({ where: { slug: SLUG }, include: { links: true } });
  if (!p) throw new Error(`no problem ${SLUG}`);
  if (p.status !== "pending") throw new Error(`${SLUG} is ${p.status}, not pending`);

  const row = p as unknown as Record<string, unknown>;
  const data: Record<string, unknown> = {};
  const changes: { field: string; oldValue: string | null; newValue: string | null }[] = [];
  const fmt = (v: unknown) => (v === null || v === undefined ? null : String(v));

  let bad = 0;
  for (const e of EDITS) {
    const limit = LIMITS.get(e.key);
    if (limit && typeof e.value === "string" && e.value.length > limit) {
      console.log(`  ${e.key} OVER BY ${e.value.length - limit} (${e.value.length}/${limit})`);
      bad++;
    }
    if (fmt(row[e.key]) === fmt(e.value)) continue;
    data[e.key] = e.value;
    changes.push({ field: e.field, oldValue: fmt(row[e.key]), newValue: fmt(e.value) });
  }

  console.log(`${SLUG}: approve (edited)\n`);
  for (const c of changes) {
    const short = (s: string | null) =>
      s === null ? "(empty)" : s.length > 88 ? `${s.slice(0, 88)}...` : s;
    console.log(`  ${c.field}:\n    - ${short(c.oldValue)}\n    + ${short(c.newValue)}`);
  }
  console.log(`\n  links: ${p.links.length} -> ${LINKS.length}`);
  console.log(
    `  unchanged: verification=${p.verification}, ai=${p.aiContribution}, publication=${p.publication}, yearPosed=${p.yearPosed}`,
  );
  console.log(`  message: ${MESSAGE.length} chars (max ${MESSAGE_MAX})`);
  if (MESSAGE.length > MESSAGE_MAX) bad++;
  if (bad) throw new Error("fix the flagged fields before applying");

  if (!APPLY) {
    console.log("\nDRY RUN - pass --apply to write");
    return;
  }

  await prisma.$transaction([
    prisma.problem.update({
      where: { id: p.id },
      data: {
        ...data,
        links: { deleteMany: {}, create: LINKS.map((l, position) => ({ ...l, position })) },
        status: "published",
        reviewedAt: new Date(),
        reviewMessage: MESSAGE,
        reviewReason: "edited",
      },
    }),
    ...(changes.length
      ? [
          prisma.problemActivity.createMany({
            data: changes.map((c) => ({
              problemId: p.id,
              userId: admin.id,
              userName: admin.pseudonym ?? null,
              type: "updated" as const,
              field: c.field,
              oldValue: c.oldValue,
              newValue: c.newValue,
            })),
          }),
        ]
      : []),
    prisma.problemActivity.create({
      data: {
        problemId: p.id,
        userId: admin.id,
        userName: admin.pseudonym ?? null,
        type: "approved",
      },
    }),
    ...(p.submittedById
      ? [
          prisma.directMessage.create({
            data: {
              userId: p.submittedById,
              senderId: admin.id,
              senderName: admin.pseudonym ?? null,
              kind: "decision",
              reason: "edited",
              body: MESSAGE,
              problemId: p.id,
            },
          }),
        ]
      : []),
  ]);

  const left = await prisma.problem.count({ where: { status: "pending" } });
  const published = await prisma.problem.count({ where: { status: "published" } });
  console.log(`APPLIED - ${left} pending, ${published} published`);
}

main().finally(() => prisma.$disconnect());
