// Approve the Nevanlinna half-plane counterexample. 27 Aug 2026.
//
// Source verified: arXiv:2608.26062v1 [math.CV], 26 Aug 2026, "Three omitted
// values and non-Blaschke point divisors in half-planes", Tang, Cui, He, Hu,
// Li, Wang and Yu - all seven names match the submission. Not a duplicate.
//
// Disclosure is exemplary and appears twice: in the ABSTRACT ("The core
// construction and proof were generated during an autonomous run of GPT-5.6
// Sol Ultra") and in a dedicated section 1.2, "Declaration of AI usage", which
// gives the run length to the second - 7 h 14 min 14 s - and says the candidate
// proof was then subjected to human checking, auditing and revision, with the
// first manuscript draft also AI-generated. ai-discovered stands: an autonomous
// run produced the construction, and for a disproof the construction is the
// result.
//
// The concurrency claim checks out, and better than the submission knew.
// Section 1.1, "Chronology and priority", documents it: Tang et al. archived a
// timestamped candidate proof on GitHub on 24 August (release verified live
// here), He and Zhang's independent preprint reached arXiv on 25 August
// (arXiv:2608.24829, verified). What the submission did NOT say is that
// He-Zhang is ALSO AI-involved - its acknowledgements read "This counterexample
// was obtained through AI-assisted exploration under the authors' mathematical
// supervision and guidance." So unlike the Gromov volume-growth entry, where
// the first public proof was the non-AI one, here BOTH concurrent proofs have a
// model in the loop. That is worth recording rather than leaving implicit.
//
// One attribution refinement. posedBy "Rolf Nevanlinna" / 1925 is right for the
// origin, but the precise modern statement the paper answers is not
// Nevanlinna's own wording: the paper says Eremenko, Kulikov and Sodin
// "recently returned to this question and explicitly recorded it" as Question 2
// of arXiv:2604.06136 (verified - "When a meromorphic function that omits three
// values is of bounded type"). Kept Nevanlinna and 1925, with the modern
// formulation in the ageNote and linked, so credit lands in both places.
//
// solveDate 2026-08-24 kept: the site dates when the problem fell, and that is
// the timestamped archive date, which is also earlier than He-Zhang's arXiv
// submission.
//
// Dry run by default. Pass --apply to write.

import { PrismaClient } from "@prisma/client";
import { CURATOR_FIELDS, EDITABLE_FIELDS } from "../src/lib/editable";
import { MESSAGE_MAX } from "../src/lib/messages";

const prisma = new PrismaClient();
const APPLY = process.argv.includes("--apply");
const SLUG = "nevanlinna-s-half-plane-omitted-values-problem";
const LINK_LABEL_MAX = 120;

const LIMITS = new Map<string, number>();
for (const s of [...EDITABLE_FIELDS, ...CURATOR_FIELDS]) if (s.maxLength) LIMITS.set(s.key, s.maxLength);

const NEXT: Record<string, unknown> = {
  aiRole:
    "Disclosed twice, in the abstract and in a dedicated section 1.2 \"Declaration of AI usage\": \"The core mathematical construction and proof underlying this paper were generated during an autonomous run of GPT-5.6 Sol using OpenAI's ultra setting. The run lasted 7 hours, 14 minutes, and 14 seconds. The resulting candidate proof was subsequently subjected to human checking, mathematical auditing, and revision. The initial draft of the manuscript was also generated by AI and was subsequently reviewed and lightly revised by the authors.\" For a disproof the construction is the whole result, and an autonomous run produced it, so this is AI-discovered on the authors' own account.\n\nWorth noting alongside: the independent concurrent counterexample of He and Zhang is also AI-involved, its acknowledgements stating that \"This counterexample was obtained through AI-assisted exploration under the authors' mathematical supervision and guidance\" - though it names no model. Both routes to this century-old problem, within two days of each other, had a model in the loop.",
  verificationNote:
    "An arXiv preprint (v1, 26 August 2026, math.CV), unrefereed, with no formalization and no computational certificate, so there was nothing mechanical to re-run here and no mathematics was checked. What was verified on 27 August 2026: the paper exists at arXiv:2608.26062 with the title and all seven authors this entry lists; the AI declaration is quoted above verbatim from section 1.2; the problem it answers is real and traceable to Eremenko, Kulikov and Sodin's Question 2 (arXiv:2604.06136, confirmed by title and authors); the concurrent work of He and Zhang exists at arXiv:2608.24829 dated 25 August and does contain its own AI-assistance statement; and the timestamped GitHub release of 24 August that the priority claim rests on resolves and is live. So the chronology the paper asserts is independently checkable, which is more than most priority claims offer.",
  ageNote:
    "The question goes back to Nevanlinna's 1925 work on value distribution in angular domains, which is the date recorded here. Its precise modern form is not his wording, though: the paper notes that Eremenko, Kulikov and Sodin \"recently returned to this question and explicitly recorded it\" as Question 2 of arXiv:2604.06136, and that is the statement answered in the negative.",
  significance: 45,
  significanceNote:
    "A question traceable to Nevanlinna's 1925 work, open for a century, and live enough that Eremenko, Kulikov and Sodin restated it explicitly in 2026 - a named problem in classical value-distribution theory with real pedigree rather than a corner case. Two groups answered it independently within two days, itself a mark of the attention it was getting. Placed with the KLS quadratic-forms band at 45: above the specialist complex-geometry entries in the twenties and thirties, below the Carathéodory and Yau-Tian-Donaldson tier at 55-60.",
};

const LINKS = [
  {
    label: "Eremenko, Kulikov, Sodin - where the problem is explicitly recorded (Question 2)",
    url: "https://arxiv.org/abs/2604.06136",
    kind: "problem-record",
  },
  {
    label: "Timestamped candidate-proof archive, 24 Aug 2026 (the priority record)",
    url: "https://github.com/QuanyuTang/three-omitted-values-bounded-type-candidate-proof/releases/tag/private-archive-2026-08-24-v1",
    kind: "other",
  },
];

const DECISION = `Published as submitted - accurate throughout, and one of the better-documented entries in the catalog. Three additions rather than corrections.

The disclosure is exemplary and I quoted it in full rather than paraphrasing: abstract plus a dedicated "Declaration of AI usage", with the autonomous run timed to the second. AI-discovered stands, for the clean reason that in a disproof the construction is the result and an autonomous run produced it.

The first addition is something your note did not mention, and it strengthens the entry. He and Zhang's independent counterexample is ALSO AI-involved - their acknowledgements say it "was obtained through AI-assisted exploration under the authors' mathematical supervision and guidance", though they name no model. So unlike the Gromov volume-growth entry, where the first public proof turned out to be the non-AI one, here both routes to a century-old problem within two days had a model in the loop. That is now in the AI-role note.

Second, I verified the priority chronology rather than taking it on trust, because it is the kind of claim that usually cannot be checked: the timestamped GitHub release of 24 August resolves and is live, and He-Zhang's arXiv v1 is dated 25 August. Your framing was right, and it is now recorded as independently checkable.

Third, an attribution refinement. Nevanlinna and 1925 stay as the origin, but the precise statement being answered is Eremenko, Kulikov and Sodin's Question 2 (arXiv:2604.06136), which the paper says they "recently returned to and explicitly recorded". That is now in an age note and linked, so both the origin and the modern formulation get credit.

Also filled: verification note, significance 45. Nothing was checked mathematically - no formalization, no certificate - and the entry says so.`;

async function main() {
  const cur = await prisma.problem.findUnique({
    where: { slug: SLUG },
    select: { id: true, status: true, submittedById: true, significance: true, aiContribution: true },
  });
  if (!cur) throw new Error("submission not found");
  if (cur.status !== "pending") throw new Error(`status is ${cur.status}`);

  const curator = await prisma.user.findFirst({ where: { pseudonym: "Rasmus Lindahl" }, select: { id: true, pseudonym: true } });
  if (!curator) throw new Error("curator not found");

  let bad = 0;
  for (const [k, v] of Object.entries(NEXT)) {
    const lim = LIMITS.get(k);
    if (lim && typeof v === "string") {
      console.log(`  ${k}: ${v.length}/${lim}`);
      if (v.length > lim) { console.log(`  OVER BY ${v.length - lim}`); bad++; }
    }
  }
  for (const l of LINKS) {
    console.log(`  link label: ${l.label.length}/${LINK_LABEL_MAX}`);
    if (l.label.length > LINK_LABEL_MAX) { console.log("  LABEL OVER"); bad++; }
  }
  console.log(`  decision: ${DECISION.length}/${MESSAGE_MAX}`);
  if (DECISION.length > MESSAGE_MAX) bad++;
  if (bad) throw new Error("limits exceeded");

  console.log(`\n${SLUG} (${cur.status})`);
  console.log(`  aiContribution : ${cur.aiContribution} (unchanged)`);
  console.log(`  significance   : ${cur.significance} -> ${NEXT.significance}`);
  console.log(`  ${Object.keys(NEXT).length} fields set, +${LINKS.length} links, status -> published`);

  if (!APPLY) { console.log("\nDRY RUN - pass --apply to write"); return; }

  const nLinks = await prisma.problemLink.count({ where: { problemId: cur.id } });
  await prisma.$transaction([
    prisma.problem.update({
      where: { id: cur.id },
      data: {
        ...NEXT, status: "published", reviewedAt: new Date(), reviewMessage: DECISION, reviewReason: "as-submitted",
        links: { create: LINKS.map((l, i) => ({ ...l, position: nLinks + i })) },
      } as never,
    }),
    prisma.problemActivity.create({
      data: { problemId: cur.id, userId: curator.id, userName: curator.pseudonym, type: "approved" },
    }),
    prisma.directMessage.create({
      data: { userId: cur.submittedById!, senderId: curator.id, senderName: curator.pseudonym, kind: "decision", reason: "as-submitted", body: DECISION, problemId: cur.id },
    }),
  ]);
  console.log("\nPUBLISHED");
}

main().finally(() => prisma.$disconnect());
