// Batch review of the twelve pending submissions, 17 Aug 2026.
//
// Eleven publish, one is a duplicate. Verified per entry (sources fetched,
// disclosures read from LaTeX where the source is arXiv):
//
//  c1p      Zenodo 21898823 real (Nowicki + "Eve"); CMP hardness paper
//           (arXiv:0912.0309) confirms the parameter classification this
//           closes. Kept Candidate: self-published Zenodo with no
//           independent check, submitter themselves asked for it.
//  emd      Repo cloned at v0.1.0: 77 Lean files, zero sorry/admit, zero
//           axiom declarations, zero native_decide, toolchain v4.32.1.
//           Not compiled here. Self-posed 2026 question - low significance.
//  lsr2     Remark 2 confirmed VERBATIM in the L-S LaTeX. Their exact sympy
//           certificate and their independent mpmath check were both run
//           here: m = -4/95 - 1188*sqrt(90709)/8617355 < 0, sign certified
//           by minimal polynomial. Upgraded to site-confirmed.
//  banach   arXiv:2608.13536 (Lu-Yang) real; AI declaration verbatim as
//           submitted. The famous 1932 problem, completed. VibeGene's
//           submission is a day earlier and fuller than NimbleRaven553's -
//           the latter is rejected as the duplicate.
//  ppt      arXiv:2608.13551 (Park) real; AI statement verbatim, vague on
//           steps, so ai-assisted (the lower tier) is right as submitted.
//  szek     arXiv:2608.03815 (Chen-Nie-Xu) real; declaration verbatim
//           (Section 3 cone-inclusion lemmas generated by the model).
//           utm_source tracking stripped from the source URL.
//  tourn    Zenodo 21959291 real (Howard-Stanley). Self-posed, resolved the
//           same week; published at the floor with the caveat that no
//           prior-art sweep was done by anyone. ALL-CAPS name fixed.
//  makeev   Repo real and substantial (596 files across four independent
//           approaches: Magma certificates, interval-arithmetic C++,
//           tensor certificates). Problem record links check out
//           (Makeev via arXiv:math/9809165, Handbook ch. 21).
//  stephan  Entry arrived NAMED AFTER A PERSON ("Ralf Stephan") - renamed,
//           slug included (safe while pending). Submitted lean-verified,
//           but its own note says the check rests on a massive
//           native_decide - which is exactly what the site's tier split
//           exists for - and no public Lean repository is linked at all,
//           so it lands at Unreviewed until the artifact is public.
//  bbf      arXiv:2608.11930 (Ivanov) real, verification repo in the
//           paper's own footnote. NO AI disclosure in the paper - the
//           claim rests on the author's public statements, recorded as
//           such. Submitted expert-verified on the strength of the
//           author's own LinkedIn post: that is self-endorsement, not
//           independent expert verification - down to Unreviewed.
//           ai-assisted raised to ai-co-developed per the author's own
//           account ("ChatGPT proving most of it" under human direction).
//  wowii    The two-lemma argument was RE-DERIVED here in full - it is
//           elementary and correct (a diametral path is a shortest path,
//           hence induced, giving t >= D+1 >= A+1; an independent
//           neighbourhood set plus its centre induces a star, giving
//           t >= L+1; then A+L <= 2t-2 so ceil((A+L)/3) <= t). Upgraded
//           to site-confirmed; stays Candidate because Conjecture 72's
//           canonical wording is unpinned, which the entry says honestly.
//
// Dry run by default. Pass --apply to write.

import { PrismaClient } from "@prisma/client";
import { CURATOR_FIELDS, EDITABLE_FIELDS } from "../src/lib/editable";
import { MESSAGE_MAX } from "../src/lib/messages";

const prisma = new PrismaClient();
const APPLY = process.argv.includes("--apply");
const ADMIN_EMAIL = "rasmus.lindahl1996@gmail.com";

const LIMITS = new Map<string, number>();
for (const s of [...EDITABLE_FIELDS, ...CURATOR_FIELDS]) if (s.maxLength) LIMITS.set(s.key, s.maxLength);

interface Decision {
  slug: string;
  action: "approve" | "reject";
  reason?: string;
  newSlug?: string;
  edits?: Record<string, unknown>;
  links?: { label: string; url: string; kind: string }[];
  relations?: { toSlug: string; kind: string; note: string }[];
  message: string;
}

const DECISIONS: Decision[] = [
  {
    slug: "the-2-1-gapped-consecutive-ones-property-problem-is-np-complete",
    action: "approve",
    edits: {
      significance: 12,
      significanceNote:
        "The last open parameter case of a 2009 complexity classification with a real comparative-genomics motivation, open seventeen years. Specialist, and the resolution is self-published with no independent check yet - held at the specialist floor above the week-old problems.",
      verificationNote:
        "Checked by this site on 17 August 2026: the Zenodo record (21898823) is real, credited to Maciej Nowicki and \"Eve\" with the proof and verification package attached, and the prior-open status verifies - the Chauve-Manuch-Patterson hardness paper (arXiv:0912.0309) establishes the (k,delta)-C1P classification whose exceptional case this claims to close, and the linked 2011 follow-up restates it as open. The reduction itself was not checked here, and no independent review exists; a self-published record by a pseudonymous-branded author stays Candidate until the proof is checked by someone.",
    },
    message:
      "Published as Candidate / Unreviewed, exactly as you suggested - and thank you for suggesting it. I verified the Zenodo record and both prior-status sources: the 2009 hardness paper's classification and the 2011 restatement of the open case both check out, so the problem is real and was open. The reduction itself I did not check, and \"Eve, artificial hyperintelligence\" as a co-author is the kind of branding that makes independent checking matter more, not less - which is what Candidate is for. Significance 12. Your attribution handling (model from the account, operator as collaborator) was careful and is kept as submitted.",
  },
  {
    slug: "exact-order-three-ambiguity-of-the-einstein-maxwell-dilaton-coupling-a-2-in-metr",
    action: "approve",
    edits: {
      significance: 3,
      significanceNote:
        "A precisely posed and cleanly resolved identifiability question, but posed by this work itself in 2026 - there is no prior literature asking it. Scored at the self-posed floor; the Rainich-Misner-Wheeler lineage is context, not a pedigree.",
      verificationNote:
        "Source-audited by this site on 17 August 2026: the repository was cloned at v0.1.0 and all 77 Lean files scanned with comments stripped - zero sorry, zero admit, zero axiom declarations, zero native_decide, toolchain pinned at v4.32.1 with Mathlib. Not compiled here (the repo's CI is claimed to). Lean-checked rather than Lean-verified per this site's standing split: the statements' correspondence to the informal claims has not been independently audited, and the same pipeline produced both the proofs and the formalization. No human peer review.",
    },
    message:
      "Published as Lean-checked. I cloned the repo at v0.1.0 and audited all 77 Lean files with comments stripped: zero sorry, admit, axiom declarations or native_decide, on the pinned v4.32.1 toolchain - a clean package, and the claim-ledger discipline from your larger program shows. Two things to be straight about. Significance is 3: the question is precisely posed and cleanly resolved, but it is posed by this work itself - the site scores the problem as it stood before the solve, and a 2026 self-posed question has no standing yet, however good the lineage. And the tier is Lean-checked rather than Lean-verified because nobody independent has audited the statement-to-claim correspondence - same rule as every autonomous formalization here. When the arXiv preprint lands, message me and Publication moves up. This clears the publication threshold on its own merits; the feedback I would give for next time is exactly what you already did - self-contained extraction, pinned toolchain, honest boundaries.",
  },
  {
    slug: "lorist-schwenninger-remark-2-positivity-question",
    action: "approve",
    edits: {
      verification: "site-confirmed",
      significance: 4,
      significanceNote:
        "A question posed ten days earlier, in a remark of the Lorist-Schwenninger Crouzeix paper - real, precisely stated, and worth settling because it delimits what their inequality (5) can do alone, but it is a fresh aside rather than a standing problem. Below the Graffiti anchor at 5.",
      verificationNote:
        "Reproduced by this site on 17 August 2026. Remark 2 was confirmed verbatim in the Lorist-Schwenninger LaTeX source, including the exact sentence \"it is unclear whether Re<E_1 Tx,x> >= 0 in general\". The counterexample repository pins the claim in a statement file and was run here: the exact sympy certificate gives m = -4/95 - 1188*sqrt(90709)/8617355 = -0.0836..., with the sign certified through its minimal polynomial rather than floating point, and the independent mpmath implementation (no shared code) agrees; both also confirm the paper's own bounds still hold at the witness, so the counterexample refutes the remark's hope without touching Lemma 1. The mechanism note - the domain centre and numerical-range centre must separate - matches what the certificate shows. No human peer review; the tier records this site's own reproduction.",
    },
    relations: [
      {
        toSlug: "crouzeix-s-conjecture",
        kind: "builds-on",
        note: "Answers a question from Remark 2 of Lorist-Schwenninger's second Crouzeix proof: inequality (5) alone cannot give the sharp constant, since Re<E_1 Tx,x> can be negative.",
      },
    ],
    message:
      "Published, upgraded to Site-confirmed. I confirmed Remark 2 verbatim in the L-S source, then ran both your certificates on my machine: the exact sympy sign certificate (minimal polynomial and all) and the independent mpmath build agree that m < 0, and both confirm the paper's own bounds still hold at the witness. Your statement.md pinning discipline made this a ten-minute check. Significance 4 - a precisely stated question, but one posed ten days before you answered it, so it sits just under the Graffiti anchor. Also drew the relation to the Crouzeix entry, since this delimits what the second proof's inequality (5) can do alone. Five for five on submissions that survive checking.",
  },
  {
    slug: "banach-s-isometric-conjecture",
    action: "approve",
    edits: {
      significance: 40,
      significanceNote:
        "Posed by Banach himself in 1932, open 94 years, with Gromov's even-dimensional theorem (1967) the landmark partial result and a literature of odd-dimensional cases since. A famous named conjecture recognisable well outside convex geometry - placed with Sendov at 40, below the household band.",
      verificationNote:
        "Checked by this site on 17 August 2026 against the paper's LaTeX (arXiv:2608.13536, Lu-Yang, 21 pages). The AI declaration is verbatim as this entry quotes it: the authors reduced the problem to one theorem before using AI, the approach to that theorem emerged through interactions with ChatGPT 5.5 Pro and 5.6 Pro, and GPT-5.6 Sol drafted Section 3 and parts of Section 2, subsequently checked and rewritten by the authors. The mathematics - bundle topology plus Brouwer degree - was not checked here and needs a geometer. One-day-old preprint, no independent review.",
      ageNote:
        "Posed in Banach's 1932 book. Gromov proved the even-dimensional case in 1967; odd cases fell piecemeal (n=3 Auerbach-Mazur-Ulam earlier, later 4k+1 cases and more). Open 94 years in full.",
    },
    message:
      "Published at significance 40 - level with Sendov. I read the AI declaration in the paper's LaTeX and it is verbatim as you quoted: reduction first, then the key theorem's approach through ChatGPT interactions, then a model-drafted Section 3 checked and rewritten. ai-co-developed is exactly right. A 94-year-old question of Banach's completed with a model in the loop is among the largest entries this catalog has taken; the mathematics itself needs a geometer, so Unreviewed stands. Note: a second submission of the same result arrived a day after yours and was closed as a duplicate.",
  },
  {
    slug: "banach-isometric-conjecture",
    action: "reject",
    reason: "duplicate",
    message:
      "This is a duplicate: the same result (arXiv:2608.13536) was submitted a day earlier and is now published as \"Banach's isometric conjecture\", so the catalog credits that submission. Nothing wrong with yours - the earlier one simply came first and carried the fuller AI-role detail. The published entry is open to community edits if you think it misses something, and your submissions are welcome as always.",
  },
  {
    slug: "every-ppt-channel-has-finite-entanglement-breaking-index",
    action: "approve",
    edits: {
      significance: 25,
      significanceNote:
        "The eventual entanglement-breaking question for PPT channels sits directly beside the PPT-squared conjecture, one of entanglement theory's best-known open problems since 2012. Resolving eventual-EB in full generality is a real advance the field will use; the PPT-squared conjecture itself remains open, which caps it below the 30 band.",
      verificationNote:
        "Checked by this site on 17 August 2026 against the paper's LaTeX (arXiv:2608.13551, Park, 14 pages). The AI statement is verbatim as this entry describes: ChatGPT for language, LaTeX and exploratory mathematical discussions, with some ideas in the splitting section arising during interactions with GPT-5.6 Sol. That is a vague disclosure, and the site's rule takes the lower tier, so ai-assisted stands. The proof was not checked here. One-day-old preprint, no independent review.",
      resultNote:
        "Establishes that every PPT channel is eventually entanglement-breaking (finite EB index), in full generality, and bounds the index by 3 uniformly in dimension for a family strictly containing the 2-superpositive maps. The PPT-squared conjecture itself - index at most 2 - remains open; the paper presents its results as strong evidence toward the cubed version.",
    },
    message:
      "Published. The AI statement checks out verbatim in the LaTeX, and your ai-assisted call is right by the site's vague-disclosure-takes-lower-tier rule. I added a result note making the scope explicit - eventual entanglement-breaking resolved in full, PPT-squared itself still open - and set significance 25: beside one of entanglement theory's best-known conjectures without resolving it.",
  },
  {
    slug: "uniform-szekelyhidi-conjectures-for-complex-hessian-equations-on-projective-mani",
    action: "approve",
    edits: {
      sourceUrl: "https://arxiv.org/abs/2608.03815",
      significance: 20,
      significanceNote:
        "Szekelyhidi's Nakai-Moishezon-type criteria for complex Hessian equations are a standing target in Kahler geometry with a real partial-results literature. This settles a broad class (strictly right-Noetherian polynomials) on projective manifolds - substantial, specialist, partial.",
      verificationNote:
        "Checked by this site on 17 August 2026 against the paper's LaTeX (arXiv:2608.03815, Chen-Nie-Xu). The declaration is verbatim as this entry describes: the Section 3 cone-inclusion lemma proofs are revised versions of arguments generated by ChatGPT 5.6 Sol, checked and edited by the authors, and the model was also used to find gaps in an earlier version - the v2 comment records that a gap in v1 (omega not a priori Kahler) was fixed, which is worth knowing when weighing a fresh preprint. The mathematics was not checked here. No independent review.",
    },
    message:
      "Published. The declaration is verbatim in the LaTeX - named model-generated lemma proofs inside a human-led argument is the ai-co-developed definition - and your Partial call is right. Two small edits: the source URL had a chatgpt.com tracking parameter, now stripped, and the verification note records that v2 fixes a gap in v1, which a reader weighing a fresh preprint deserves to know. Significance 20.",
  },
  {
    slug: "score-determined-induced-tournament-statistics-an-all-orders-classification-and-",
    action: "approve",
    edits: {
      name: "Score-Determined Induced Tournament Statistics: an All-Orders Classification",
      shortName: "Score-determined tournament statistics",
      field: "Tournament theory",
      significance: 3,
      significanceNote:
        "A clean and natural classification question, but self-posed and resolved in the same work - no prior literature poses it. Scored at the self-posed floor, and no systematic prior-art sweep has been done by the author or this site, so even novelty is unconfirmed.",
      verificationNote:
        "Checked by this site on 17 August 2026: the Zenodo reproducibility archive (21959291, Howard-Stanley) is real and carries the manuscript and code. The classification itself was not checked here, no independent review exists, and - flagged plainly - nobody has swept the tournament-theory literature for prior appearances of this question, which for a self-posed problem is the main risk. The disclosure (\"absolutely everything, I occasionally steered\") is the frankest ai-discovered claim in the catalog.",
    },
    message:
      "Published, with the name brought down from all-caps and significance set at 3. Being straight about why the floor: the question is natural and the archive is real, but it is self-posed and solved in the same work, and neither you nor I have swept the literature for prior appearances - for a self-posed classification, that is the main risk, and the verification note says so. Your disclosure is the frankest ai-discovered claim in the catalog, which is worth something. If the question turns out to have prior standing in the literature, message me and the significance moves.",
  },
  {
    slug: "makeev-s-conjecture-on-universal-cover",
    action: "approve",
    edits: {
      significance: 15,
      significanceNote:
        "A named 1994 conjecture in metric geometry, recorded in the Handbook of Discrete and Computational Geometry's problem chapter, in the universal-covers tradition of Lebesgue's problem. Real and thirty-two years old, but specialist: level with the named specialist band at 15.",
      verificationNote:
        "Checked by this site on 17 August 2026: the repository is real and unusually substantial - 596 files across four independently-built verification approaches (Magma certificates, interval-arithmetic C++, tensor-polynomial certificates, Python numerics), plus the full prompts and chat transcripts, and the problem-record links verify (Makeev's conjecture in arXiv:math/9809165, Handbook chapter 21). The certificates were not run here. The submitter reports a preliminary check by two students, which is private checking, not independent review - Unreviewed stands.",
    },
    message:
      "Published. The repository is genuinely impressive - four independently-built verification routes plus full prompts and transcripts is more provenance than most arXiv preprints carry - and both problem-record links verify. I did not run the certificates, and the student checks are private, so Unreviewed stands for now; a public endorsement or a site rerun of the interval-arithmetic certificate would move it. Significance 15 for a named 32-year-old Handbook conjecture.",
  },
  {
    slug: "ralf-stephan",
    action: "approve",
    newSlug: "composites-among-xi-7-n",
    edits: {
      name: "Composites Among $[\\xi 7^n]$ and Right-Truncatable Primes in Base 7",
      shortName: "Composites among $[\\xi 7^n]$",
      field: "Number theory - integer sequences",
      fieldGroup: "Number theory",
      verification: "unreviewed",
      significance: 10,
      significanceNote:
        "A concrete question in the Forman-Shapiro tradition, posed for base 7 by Dubickas and Novikas in 2005 and open twenty-one years. Specialist but genuinely standing - level with the numbered-Erdos band at 10.",
      verificationNote:
        "Reviewed by this site on 17 August 2026. The entry arrived titled with a person's name and claiming Lean-verified; both needed correcting. The submitter's own note says the Lean check rests on a massive native_decide certificate check - native_decide bypasses the kernel through the compiled evaluator, which is precisely the distinction this site's tier ladder exists to record - and, more fundamentally, no public Lean repository is linked anywhere on the entry: the only artifact is a ResearchGate manuscript. A formalization that cannot be fetched cannot hold any Lean tier, so this sits at Unreviewed. If the Lean development is published (with its native_decide dependence stated), the tier can move to Lean-checked on a source audit.",
    },
    message:
      "Published, with a rename and a tier correction. The entry arrived titled \"Ralf Stephan\" - a person, not a problem - and is now named for the statement. The bigger correction: Lean-verified cannot stand, for two independent reasons. Your own note says the check rests on a massive native_decide, which bypasses the kernel through the compiled evaluator - this site's ladder treats that as below kernel-checked, and every Lean audit here counts native_decide occurrences for exactly that reason. And no public Lean repository is linked at all; the only artifact is a ResearchGate manuscript, and a formalization nobody can fetch cannot hold a Lean tier. Publish the Lean development and message me - a source audit moves it to Lean-checked the same day. Significance 10 for a 2005 Dubickas-Novikas question in the Forman-Shapiro tradition.",
  },
  {
    slug: "strong-graph-reconstruction-conjecture",
    action: "approve",
    edits: {
      posedBy: "Andrew Bowler, Paul Brown, Trevor Fenner",
      yearPosed: 2010,
      field: "Graph theory - reconstruction",
      fieldGroup: "Combinatorics",
      verification: "unreviewed",
      aiContribution: "ai-co-developed",
      significance: 20,
      significanceNote:
        "The Strong Reconstruction Conjecture of Bowler, Brown and Fenner is the quantitative frontier of the reconstruction-number literature around the celebrated Kelly-Ulam problem. Disproving it, and showing overlap can approach the full deck, reshapes that frontier - specialist but consequential, at 20.",
      verificationNote:
        "Checked by this site on 17 August 2026 against the paper's LaTeX (arXiv:2608.11930, Ivanov) and its verification repository, which the paper's own footnote links. Two submitted claims needed correcting. The entry arrived Expert-verified on the strength of the author's own LinkedIn post - self-endorsement is not independent expert verification, so this is Unreviewed. And the paper itself contains NO AI disclosure: the account of GPT-5.6 Sol's role rests entirely on the author's public statements outside the paper, which this entry now says explicitly. The nauty deck checks are author-side. The construction was not verified here.",
      aiRole:
        "Per the author's public statements (not disclosed in the paper itself): GPT-5.6 Sol proved most of the roughly 400 intermediate theorems explored, with the author supplying the decisive construction idea and direction - in the author's words, the models \"could not achieve the goal before I can point to the right idea\". Model-proved steps inside a human-led search is recorded as ai-co-developed.",
      resultNote:
        "Disproves the Bowler-Brown-Fenner bound of 2*floor((n-1)/3) on common cards between nonisomorphic graphs: an explicit connected 78-vertex pair shares at least 51 cards against the predicted 50, and for every even r >= 4 there are families with overlap fraction asymptotically at least 1 - 1/r, so the attainable fraction approaches the full deck. The Kelly-Ulam reconstruction conjecture itself is untouched.",
    },
    message:
      "Published, with two corrections you should know about. Expert-verified came down to Unreviewed: the verification link was your own LinkedIn post, and self-endorsement is not independent expert verification - when a reconstruction-number specialist publicly checks the construction, the tier moves. Second, the paper itself carries no AI disclosure, so the account of the model's role rests on your public statements, and the entry now says that explicitly; adding a disclosure to the arXiv v2 would fix it at the source. I also moved ai-assisted up to ai-co-developed on your own description - a model that proved most of 400 intermediate theorems under your direction did more than tooling - and set significance 20. Your learnings note was genuinely useful; the 10^789 framing of why this needed mathematics rather than search belongs in the paper.",
  },
  {
    slug: "wowii-conjecture-72-two-induced-trees-pin-down-tree-g",
    action: "approve",
    edits: {
      verification: "site-confirmed",
      significance: 5,
      significanceNote:
        "A machine-generated conjecture from DeLaViña's Written on the Wall II list - exactly the catalog's Graffiti anchor at 5. Open since around 2001 and part of the current wave of WOWII resolutions.",
      verificationNote:
        "Re-derived in full by this site on 17 August 2026 - the argument is elementary and correct, and short enough to state: a shortest path between two vertices at maximum distance D is induced, so it induces a path (a tree) on D+1 vertices, giving tree(G) >= D+1 >= A+1 since average eccentricity is at most D; a maximum independent set in a neighbourhood plus its centre induces a star on L+1 vertices, giving tree(G) >= L+1; hence A + L <= 2*tree(G) - 2, and ceil((A+L)/3) <= tree(G) follows by integrality. The stronger reading (dividing only L by three) fails on the claimed counterexample family. What keeps this Candidate is not the mathematics but the statement: Conjecture 72's canonical wording is not publicly pinned (no formal statement exists in the Formal Conjectures repository), so which reading DeLaViña intended is unconfirmed, and the X post plus transcript is the only artifact. Site-confirmed records this site's independent re-derivation of the proved reading.",
    },
    message:
      "Published, and upgraded to Site-confirmed - because the argument is short enough that I simply re-derived it. Diametral shortest path is induced, so t >= D+1 >= A+1; independent neighbourhood set plus centre is an induced star, so t >= L+1; add and divide. Both lemmas and the integer arithmetic check out, so the evenly-divided reading is a theorem regardless of what happens to the artifact trail. Candidate stays, though, for the reason your note already gives: Conjecture 72's canonical wording is not publicly pinned, so which reading DeLaViña intended is unconfirmed - the entry is honest about resolving a reading rather than a pinned statement. If the Formal Conjectures repo lands a GraphConjecture72.lean, message me. Significance 5, the catalog's exact Graffiti anchor.",
  },
];

async function main() {
  const admin = await prisma.user.findUnique({ where: { email: ADMIN_EMAIL } });
  if (!admin) throw new Error("no admin");

  let bad = 0;
  for (const d of DECISIONS) {
    if (d.message.length > MESSAGE_MAX) {
      console.log(`  MESSAGE OVER on ${d.slug}: ${d.message.length}`);
      bad++;
    }
    for (const [k, v] of Object.entries(d.edits ?? {})) {
      const lim = LIMITS.get(k);
      if (lim && typeof v === "string" && v.length > lim) {
        console.log(`  ${d.slug}.${k} OVER BY ${v.length - lim} (${v.length}/${lim})`);
        bad++;
      }
    }
  }
  if (bad) throw new Error("limits exceeded - fix before applying");

  for (const d of DECISIONS) {
    const p = await prisma.problem.findUnique({ where: { slug: d.slug }, include: { links: true } });
    if (!p) throw new Error(`no entry ${d.slug}`);
    if (p.status !== "pending") {
      console.log(`  skip ${d.slug}: already ${p.status}`);
      continue;
    }

    const row = p as unknown as Record<string, unknown>;
    const fmt = (v: unknown) =>
      v === null || v === undefined ? null : Array.isArray(v) ? v.join(", ") : String(v);
    const data: Record<string, unknown> = {};
    const changes: { field: string; oldValue: string | null; newValue: string | null }[] = [];
    for (const [k, v] of Object.entries(d.edits ?? {})) {
      if (fmt(row[k]) === fmt(v)) continue;
      data[k] = v;
      changes.push({ field: k, oldValue: fmt(row[k]), newValue: fmt(v) });
    }
    if (d.newSlug) {
      data.slug = d.newSlug;
      changes.push({ field: "URL slug", oldValue: d.slug, newValue: d.newSlug });
    }

    console.log(`\n=== ${d.action.toUpperCase()} ${d.slug}`);
    for (const c of changes) console.log(`  ${c.field}: ${String(c.newValue).slice(0, 70)}`);
    if (d.relations) for (const r of d.relations) console.log(`  relation --${r.kind}--> ${r.toSlug}`);
    console.log(`  message ${d.message.length} chars`);

    if (!APPLY) continue;

    if (d.action === "reject") {
      await prisma.$transaction([
        prisma.problem.update({
          where: { id: p.id },
          data: {
            status: "rejected",
            reviewedAt: new Date(),
            reviewMessage: d.message,
            reviewReason: d.reason ?? "other",
          },
        }),
        prisma.problemActivity.create({
          data: { problemId: p.id, userId: admin.id, userName: admin.pseudonym ?? null, type: "rejected" },
        }),
        ...(p.submittedById
          ? [
              prisma.directMessage.create({
                data: {
                  userId: p.submittedById,
                  senderId: admin.id,
                  senderName: admin.pseudonym ?? null,
                  kind: "decision",
                  reason: d.reason ?? "other",
                  body: d.message,
                  problemId: p.id,
                },
              }),
            ]
          : []),
      ]);
      continue;
    }

    let relationRows: { toId: string; kind: string; note: string; position: number }[] = [];
    if (d.relations) {
      const targets = await prisma.problem.findMany({
        where: { slug: { in: d.relations.map((r) => r.toSlug) }, status: "published" },
        select: { id: true, slug: true },
      });
      const bySlug = new Map(targets.map((t) => [t.slug, t.id]));
      relationRows = d.relations.map((r, position) => {
        const toId = bySlug.get(r.toSlug);
        if (!toId) throw new Error(`relation target missing: ${r.toSlug}`);
        return { toId, kind: r.kind, note: r.note, position };
      });
    }

    await prisma.$transaction([
      prisma.problem.update({
        where: { id: p.id },
        data: {
          ...data,
          ...(d.links ? { links: { deleteMany: {}, create: d.links.map((l, position) => ({ ...l, position })) } } : {}),
          ...(relationRows.length ? { relationsFrom: { deleteMany: {}, create: relationRows } } : {}),
          status: "published",
          reviewedAt: new Date(),
          reviewMessage: d.message,
          reviewReason: "edited",
        },
      }),
      ...(changes.length
        ? [
            prisma.problemActivity.createMany({
              data: changes.map((c) => ({
                problemId: p.id,
                userId: admin.id,
                userName: admin.pseudonym ?? null,
                type: "updated" as const,
                field: c.field,
                oldValue: c.oldValue,
                newValue: c.newValue,
              })),
            }),
          ]
        : []),
      prisma.problemActivity.create({
        data: { problemId: p.id, userId: admin.id, userName: admin.pseudonym ?? null, type: "approved" },
      }),
      ...(p.submittedById
        ? [
            prisma.directMessage.create({
              data: {
                userId: p.submittedById,
                senderId: admin.id,
                senderName: admin.pseudonym ?? null,
                kind: "decision",
                reason: d.action === "approve" ? "edited" : "other",
                body: d.message,
                problemId: p.id,
              },
            }),
          ]
        : []),
    ]);
  }

  if (APPLY) {
    const left = await prisma.problem.count({ where: { status: "pending" } });
    const published = await prisma.problem.count({ where: { status: "published" } });
    console.log(`\nAPPLIED - ${left} pending, ${published} published`);
  } else {
    console.log("\nDRY RUN - pass --apply to write");
  }
}

main().finally(() => prisma.$disconnect());
