// Add Kong-Zhu's independent proof to the Gromov volume-growth entry, 24 Aug
// 2026 - a third route to the same 1986 conjecture, within about 24 hours of
// the other two, and the second with AI explicitly in the loop.
//
// Read in full from arXiv:2608.14438 (PDF, not just the abstract - the
// disclosure sits in an "AI disclosure" section near the end, not the
// abstract, which is why an abstract-only check would have missed it):
// "Generative AI tools, more explicitly, ChatGPT 5.6 Sol Ultra and Codex,
// assisted with proof exploration, organization, and drafting. Essential
// ideas were generated by AI." The paper also states, in that same section,
// that it became aware of Ge's preprint (arXiv:2608.13553, already linked on
// this entry) during drafting, that Ge's method is "very similar", and that
// its own AI-generated proof predates Ge's becoming public and was not
// derived from it.
//
// Antonelli's paper stays primary/headline: it is already published and
// reviewed, and its scope (the general Brendle-Hirsch-Johne intermediate-
// curvature family, not only Gromov's m=n-2 case) is broader than Kong-Zhu's
// result. This is the same "concurrent proofs share one entry" handling
// already applied to Ge - a plain link, not a database relation, since
// neither Ge's nor Kong-Zhu's paper is its own catalog entry.
//
// Dry run by default. Pass --apply to write.

import { PrismaClient } from "@prisma/client";
import { CURATOR_FIELDS, EDITABLE_FIELDS } from "../src/lib/editable";
import { MESSAGE_MAX } from "../src/lib/messages";

const prisma = new PrismaClient();
const APPLY = process.argv.includes("--apply");
const SLUG = "universal-volume-growth-bounds-from-positive-intermediate-curvature";

const LIMITS = new Map<string, number>();
for (const s of [...EDITABLE_FIELDS, ...CURATOR_FIELDS]) if (s.maxLength) LIMITS.set(s.key, s.maxLength);
const LINK_LABEL_MAX = 120;

const NEXT: Record<string, unknown> = {
  resultNote:
    "Gromov's 1986 question drew three independent proofs within about 24 hours, two with AI in the loop. Ge's non-AI proof (heat-kernel Fisher metric, Nash entropy) came first, 13 August. Antonelli's proof here (14 August, GPT-5.6 Sol) takes a different route, Hodge obstruction and rank improvement, and its headline addition is the general family: for every $0\\le m\\le n-2$, nonnegative Ricci plus positive $(m{+}1)$-intermediate curvature forces at most $m$-dimensional growth - linear growth under biRicci curvature at $m=1$, plus a noncollapsed Urysohn-width bound; the author states this extension is his own, not the model's. Kong and Zhu's proof (also 14 August; GPT-5.6 Sol Ultra and Codex, \"essential ideas were generated by AI\") proves the same case plus a related codimension-one conjecture via a heat-transport deficit, close to Ge's method by its own account, produced before Ge's went public and not derived from it. Headline axes stay Antonelli's, for the broader scope.",
  verificationNote:
    "A five-day-old arXiv preprint, unrefereed and not formally endorsed, so this stays Unreviewed. It is not unexamined, though: the author thanks Elia Bruè, Otis Chodosh, Alessandro Cucinotta, Chao Li, Aaron Naber, Daniele Semola and Kai Xu for comments on preliminary versions, and the acknowledgments record two specific ways their comments changed the argument. That is a stronger signal than most preprints of this age carry, but comments are not endorsement, and this site ran no independent check of its own.\n\nThe strongest external evidence is indirect and worth stating: three independent routes converge on the same 1986 conjecture within about 24 hours - Jian Ge's heat-kernel Fisher-metric argument (13 August, no AI), this paper's Hodge-obstruction argument (14 August, GPT-5.6 Sol), and Kong-Zhu's heat-transport-deficit argument (also 14 August, GPT-5.6 Sol Ultra and Codex) - the last stating its own method is close to Ge's but developed independently and before Ge's preprint was public. None of the three has been independently checked, but three unrelated-to-mostly-unrelated routes agreeing is meaningful corroboration of the statement regardless.",
  ageNote:
    "Posed by Gromov in 1986, in section 2.A(b) of Large Riemannian manifolds. The solved date is 13 August 2026, when Jian Ge's independent proof appeared; this paper and Kong-Zhu's both followed one day later, all three written without knowledge of each other.",
  aiRole:
    "From the paper's own disclosure of AI tools. The work made substantial use of OpenAI's GPT-5.6 Sol at Ultra reasoning effort. GPT proposed the central inductive procedure, based on the Hodge obstruction and rank improvement, behind the proof of Theorem 1.1 - the scalar-curvature case, which is Gromov's question. Antonelli formulated and guided the problem, suggested strategies and literature, and developed the note from that strategy.\n\nHe is explicit about how far the published proof moved from the model's: it is effective, where the suggested strategy proceeded by contradiction, and it is much less reliant on Kapovitch-Wilking's Theorem 5.1 - both changes emerging from discussions with Daniele Semola, Elia Bruè and Kai Xu. He also states that the extension to the full Brendle-Hirsch-Johne intermediate-curvature family, which is the paper's general theorem, is his own contribution and not the model's.\n\nKong and Zhu's independent same-day proof (arXiv:2608.14438) discloses its own AI use more bluntly: \"Generative AI tools, more explicitly, ChatGPT 5.6 Sol Ultra and Codex, assisted with proof exploration, organization, and drafting. Essential ideas were generated by AI.\" That is the stronger of the two claims by wording, though for a narrower result than Antonelli's general family; the headline axes stay Antonelli's for that reason.",
};

const NEW_LINK = {
  label: "Kong and Zhu, Positive Scalar Curvature and Volume Growth (arXiv, 14 Aug 2026)",
  url: "https://arxiv.org/abs/2608.14438",
  kind: "independent",
};

const MESSAGE = `Small addition to the Gromov volume-growth entry you submitted: a third independent proof surfaced, and it belongs on the same entry.

Kong and Zhu posted "Positive Scalar Curvature and Volume Growth" on arXiv the same day as Antonelli's paper (14 August), proving the same codimension-two case by a heat-transport-deficit argument, plus a related codimension-one conjecture. Their AI disclosure is blunter than Antonelli's: "Essential ideas were generated by AI," naming ChatGPT 5.6 Sol Ultra and Codex. They also state they learned of Ge's paper during drafting, that Ge's method is close to their own, and that their AI-generated proof predates and was not derived from Ge's.

Antonelli's paper stays the entry's headline: it is already published, and its scope (the general Brendle-Hirsch-Johne family, not just this one case) is broader than Kong-Zhu's result. The result note, verification note and age note now tell the three-proof story; the AI-role note quotes Kong-Zhu's disclosure alongside Antonelli's. Nothing about the headline axes changed.`;

async function main() {
  const admin = await prisma.user.findFirst({
    where: { pseudonym: "Rasmus Lindahl" },
    select: { id: true, pseudonym: true },
  });
  if (!admin) throw new Error("no admin");

  const cur = await prisma.problem.findUnique({
    where: { slug: SLUG },
    select: {
      id: true, status: true, submittedById: true,
      resultNote: true, verificationNote: true, ageNote: true, aiRole: true,
    },
  });
  if (!cur) throw new Error("entry not found");
  if (cur.status !== "published") throw new Error(`status is ${cur.status}`);

  let bad = 0;
  for (const [k, v] of Object.entries(NEXT)) {
    const lim = LIMITS.get(k);
    console.log(`  ${k}: ${(v as string).length}/${lim}`);
    if (lim && (v as string).length > lim) {
      console.log(`  OVER BY ${(v as string).length - lim}`);
      bad++;
    }
  }
  console.log(`  link label: ${NEW_LINK.label.length}/${LINK_LABEL_MAX}`);
  if (NEW_LINK.label.length > LINK_LABEL_MAX) {
    console.log(`  LINK LABEL OVER BY ${NEW_LINK.label.length - LINK_LABEL_MAX}`);
    bad++;
  }
  console.log(`  message: ${MESSAGE.length}/${MESSAGE_MAX}`);
  if (MESSAGE.length > MESSAGE_MAX) bad++;
  if (bad) throw new Error("limits exceeded");

  const changes: { field: string; oldValue: string | null; newValue: string }[] = [
    { field: "What was actually shown", oldValue: cur.resultNote, newValue: NEXT.resultNote as string },
    { field: "Verification note", oldValue: cur.verificationNote, newValue: NEXT.verificationNote as string },
    { field: "Age note", oldValue: cur.ageNote, newValue: NEXT.ageNote as string },
    { field: "What the AI did", oldValue: cur.aiRole, newValue: NEXT.aiRole as string },
  ];

  console.log(`\n${SLUG} (published)`);
  console.log(`  +1 link (Kong-Zhu, independent)`);
  console.log(`  4 fields updated`);

  if (!APPLY) {
    console.log("\nDRY RUN - pass --apply to write");
    return;
  }

  const nLinks = await prisma.problemLink.count({ where: { problemId: cur.id } });
  await prisma.$transaction([
    prisma.problem.update({
      where: { id: cur.id },
      data: {
        ...NEXT,
        links: { create: { ...NEW_LINK, position: nLinks } },
      } as never,
    }),
    prisma.problemActivity.createMany({
      data: changes.map((c) => ({
        problemId: cur.id,
        userId: admin.id,
        userName: admin.pseudonym,
        type: "updated" as const,
        field: c.field,
        oldValue: c.oldValue,
        newValue: c.newValue,
      })),
    }),
    ...(cur.submittedById
      ? [
          prisma.directMessage.create({
            data: {
              userId: cur.submittedById,
              senderId: admin.id,
              senderName: admin.pseudonym,
              kind: "reply" as const,
              body: MESSAGE,
              problemId: cur.id,
            },
          }),
        ]
      : []),
  ]);
  console.log("\nAPPLIED");
}

main().finally(() => prisma.$disconnect());
