"""Independent verification of R_dih(P_a^alt, K_b) = 1+(a-1)(b-1), a >= 4.

Everything here is implemented from statement.md's definitions alone - the
proof's machinery, both referees' code and the shipped CNFs are not read.

Three layers:
  1. the statement's own sanity anchor: |orbit of P_a^alt under Dih(a)| = a
     for 3 <= a <= 14;
  2. the Ramsey values themselves: exhaustive over ALL 2-colorings at five
     cells, and via an independently written CNF encoding + CaDiCaL at four
     more, in both directions (a good coloring exists at n = R-1, none at
     n = R);
  3. the Aggregate Sum Theorem, checked by brute force from the P/Q
     DEFINITIONS (not the recursion the proof uses) over every labeled graph
     on up to 6 vertices - a third implementation, after the two referees'.
"""
import itertools
import sys
from functools import lru_cache

from pysat.formula import CNF
from pysat.solvers import Cadical153


# --- the objects, from statement.md ---

def alt_path(a):
    """Edges of P_a^alt: consecutive pairs of (0, a-1, 1, a-2, 2, ...)."""
    seq = []
    lo, hi = 0, a - 1
    for k in range(a):
        seq.append(lo if k % 2 == 0 else hi)
        if k % 2 == 0:
            lo += 1
        else:
            hi -= 1
    return frozenset(frozenset(p) for p in zip(seq, seq[1:]))


def dih(m):
    """Dih(m) as permutation tuples, generated by rho and sigma."""
    rho = tuple((i + 1) % m for i in range(m))
    sigma = tuple(m - 1 - i for i in range(m))
    ident = tuple(range(m))
    group = {ident}
    frontier = [ident]
    while frontier:
        nxt = []
        for g in frontier:
            for h in (rho, sigma):
                gh = tuple(h[g[i]] for i in range(m))
                if gh not in group:
                    group.add(gh)
                    nxt.append(gh)
        frontier = nxt
    return group


def orbit(a):
    """{gamma(P_a^alt) : gamma in Dih(a)} as a set of edge sets."""
    H = alt_path(a)
    out = set()
    for g in dih(a):
        out.add(frozenset(frozenset({g[i], g[j]}) for i, j in (tuple(e) for e in H)))
    return out


# --- layer 1: the sanity anchor ---
print("== orbit sizes (statement's anchor: exactly a, for 3 <= a <= 14)")
ok = True
for a in range(3, 15):
    n = len(orbit(a))
    ok &= n == a
    print(f"   a={a}: {n}")
print(f"   anchor holds: {ok}")
assert ok


# --- layer 2: the Ramsey cells ---

def has_dih_copy(a, n, color1_edges, orb):
    """Does the color-1 graph contain a Dih(a)-copy of P_a^alt?

    Per statement.md this is: some H' in the orbit admits a MONOTONE
    embedding v_0 < ... < v_{a-1} with every H'-edge landing in color 1.
    """
    for verts in itertools.combinations(range(n), a):
        for Hp in orb:
            if all(frozenset({verts[i], verts[j]}) in color1_edges
                   for e in Hp for i, j in [tuple(e)]):
                return True
    return False


def has_clique(b, n, color2_edges):
    for verts in itertools.combinations(range(n), b):
        if all(frozenset({u, v}) in color2_edges
               for u, v in itertools.combinations(verts, 2)):
            return True
    return False


def exhaustive_cell(a, b):
    """Check both sides of R = 1+(a-1)(b-1) over ALL colorings."""
    R = 1 + (a - 1) * (b - 1)
    orb = orbit(a)

    def good_coloring_exists(n):
        """A coloring with NO color-1 dih-copy and NO color-2 K_b."""
        if b == 1:
            return n == 0  # a color-2 K_1 exists whenever there is a vertex
        edges = list(itertools.combinations(range(n), 2))
        for mask in range(2 ** len(edges)):
            c1 = frozenset(frozenset(e) for k, e in enumerate(edges) if mask >> k & 1)
            c2 = frozenset(frozenset(e) for k, e in enumerate(edges) if not mask >> k & 1)
            if not has_clique(b, n, c2) and not has_dih_copy(a, n, c1, orb):
                return True
        return False

    below = good_coloring_exists(R - 1)  # must be True  -> R > R-1
    at = good_coloring_exists(R)         # must be False -> R <= R
    return R, below, at


print("\n== exhaustive cells (every 2-coloring enumerated)")
for a, b in [(4, 2), (5, 2), (6, 2), (7, 2), (4, 3)]:
    R, below, at = exhaustive_cell(a, b)
    verdict = "OK" if (below and not at) else "FAIL"
    print(f"   (a={a},b={b}): R claimed {R}; good coloring at n={R-1}: {below}; at n={R}: {at}  [{verdict}]")
    assert below and not at


def sat_cell(a, b):
    """Same check by an independently written CNF encoding, via CaDiCaL.

    Variables: one per edge of K_n (true = color 1). Clauses: for every
    orbit graph and monotone vertex choice, NOT all its edges color 1;
    for every b-subset, NOT all its pairs color 2.
    """
    R = 1 + (a - 1) * (b - 1)
    orb = orbit(a)

    def solve(n):
        var = {}
        for u, v in itertools.combinations(range(n), 2):
            var[frozenset({u, v})] = len(var) + 1
        cnf = CNF()
        for verts in itertools.combinations(range(n), a):
            for Hp in orb:
                cnf.append([-var[frozenset({verts[i], verts[j]})]
                            for e in Hp for i, j in [tuple(e)]])
        for verts in itertools.combinations(range(n), b):
            cnf.append([var[frozenset({u, v})]
                        for u, v in itertools.combinations(verts, 2)])
        with Cadical153(bootstrap_with=cnf) as s:
            return s.solve()

    return R, solve(R - 1), solve(R)


print("\n== SAT cells (own encoder, CaDiCaL)")
for a, b in [(8, 2), (5, 3), (6, 3), (4, 4)]:
    R, below, at = sat_cell(a, b)
    verdict = "OK" if (below and not at) else "FAIL"
    print(f"   (a={a},b={b}): R claimed {R}; SAT at n={R-1}: {below}; SAT at n={R}: {at}  [{verdict}]")
    assert below and not at


# --- layer 3: the Aggregate Sum Theorem, from the definitions ---

def realizes(tuple_verts, p, edges):
    """Does the increasing tuple realize P_p^alt on its natural order?"""
    P = alt_path(p)
    return all(frozenset({tuple_verts[i], tuple_verts[j]}) in edges
               for e in P for i, j in [tuple(e)])


def P_of(m, W, edges):
    best = 0
    below = [w for w in W if w < m]
    for p in range(1, len(below) + 1):
        for tup in itertools.combinations(below, p):
            if frozenset({tup[0], m}) in edges and realizes(tup, p, edges):
                best = max(best, p)
                break  # any witness of length p suffices
    return best


def Q_of(m, W, edges):
    best = 0
    above = [w for w in W if w > m]
    for q in range(1, len(above) + 1):
        for tup in itertools.combinations(above, q):
            rev = tuple(tup[q - 1 - i] for i in range(q))
            # i -> r_{q-1-i} realizes P_q^alt, attachment r_{q-1} ~ m
            if frozenset({tup[-1], m}) in edges and all(
                frozenset({rev[i], rev[j]}) in edges
                for e in alt_path(q) for i, j in [tuple(e)]
            ):
                best = max(best, q)
                break
    return best


print("\n== Aggregate Sum: sum[P(m)+Q(m)] >= 2|E| over all labeled graphs, n <= 6")
total = 0
worst_slack = None
for n in range(0, 7):
    pairs = list(itertools.combinations(range(n), 2))
    for mask in range(2 ** len(pairs)):
        edges = frozenset(frozenset(e) for k, e in enumerate(pairs) if mask >> k & 1)
        W = list(range(n))
        s = sum(P_of(m, W, edges) + Q_of(m, W, edges) for m in W)
        slack = s - 2 * len(edges)
        if slack < 0:
            print(f"   VIOLATION at n={n}, edges={sorted(map(sorted, edges))}")
            sys.exit(1)
        worst_slack = slack if worst_slack is None else min(worst_slack, slack)
        total += 1
print(f"   {total} graphs checked, zero violations, minimum slack {worst_slack}")
print(f"   (their count was 33,868; difference is whether the n=0 graph is counted)")

print("\nALL CHECKS PASSED")
